#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Add part_gt_mask_patch to VOC116 object-level feature pth.

This script is for the current Talk2DINO/VOC116 test15 data chain.

Input pth already contains:
  images[*]["file_name"]
  annotations[*]["image_id"]
  annotations[*]["part_category_id"]
  annotations[*]["part_class_name"]
  annotations[*]["cropaug_box_xyxy"]
  annotations[*]["cropaug_patch_tokens"]

This script reads the original Pascal-Part part segmentation PNGs and writes:
  annotations[*]["part_gt_mask_patch"] = BoolTensor [K, H_patch, W_patch]

No guessing of field names:
  - part_category_id is the part id list.
  - cropaug_box_xyxy is the crop box generated by dino_extraction_v2_cropaug.py.
  - part mask directory is explicitly passed by --part_mask_dir.
"""

import argparse
import os
from pathlib import Path
from typing import Any, Dict

import numpy as np
from PIL import Image
import torch
import torch.nn.functional as F
from tqdm import tqdm


def require_key(obj: Dict[str, Any], key: str, ctx: str) -> Any:
    if key not in obj:
        available = ", ".join(sorted([str(k) for k in obj.keys()]))
        raise KeyError(f"Missing key '{key}' in {ctx}. Available keys: {available}")
    return obj[key]


def resolve_part_mask_path(img_info: Dict[str, Any], part_mask_dir: Path) -> Path:
    """
    The part mask file name is matched by image stem.
    Example:
      image: .../2008_000002.jpg
      part mask: <part_mask_dir>/2008_000002.png
    """
    file_name = require_key(img_info, "file_name", "image")
    stem = Path(str(file_name)).stem
    path = part_mask_dir / f"{stem}.png"
    if not path.exists():
        raise FileNotFoundError(f"Part mask not found: {path}")
    return path


def crop_and_resize_binary_to_patch(
    binary_full: np.ndarray,
    crop_box_xyxy,
    crop_dim: int,
    patch_size: int,
) -> torch.Tensor:
    """
    binary_full: H x W numpy bool/uint8 full-image part mask.
    crop_box_xyxy: [left, top, right, bottom] in original-image coordinates.
    Return BoolTensor [crop_dim/patch_size, crop_dim/patch_size].
    """
    left, top, right, bottom = [int(x) for x in crop_box_xyxy]
    if right <= left or bottom <= top:
        raise ValueError(f"Invalid crop box: {crop_box_xyxy}")

    crop = binary_full[top:bottom, left:right].astype(np.uint8)
    if crop.size == 0:
        raise ValueError(f"Empty crop from box: {crop_box_xyxy}")

    # Resize exactly like the crop image is resized before patch extraction,
    # then max-pool each patch cell to decide whether this part occupies the patch.
    t = torch.from_numpy(crop).float().view(1, 1, crop.shape[0], crop.shape[1])
    t = F.interpolate(t, size=(crop_dim, crop_dim), mode="nearest")

    if crop_dim % patch_size != 0:
        raise ValueError(f"crop_dim={crop_dim} must be divisible by patch_size={patch_size}")
    grid = crop_dim // patch_size

    t = t.view(1, 1, grid, patch_size, grid, patch_size)
    patch = t.amax(dim=(3, 5)).view(grid, grid) > 0
    return patch.cpu()


def build_part_gt_mask_patch_for_ann(
    ann: Dict[str, Any],
    img_info: Dict[str, Any],
    part_mask_dir: Path,
    crop_dim: int,
    patch_size: int,
    with_background_part: bool,
) -> torch.Tensor:
    part_ids = require_key(ann, "part_category_id", "annotation")
    part_names = require_key(ann, "part_class_name", "annotation")
    crop_box = require_key(ann, "cropaug_box_xyxy", "annotation")

    if len(part_ids) != len(part_names):
        raise ValueError(
            f"part_category_id length {len(part_ids)} != part_class_name length {len(part_names)} "
            f"for ann id={ann.get('id', 'unknown')}"
        )

    if isinstance(crop_box, torch.Tensor):
        crop_box = crop_box.cpu().tolist()

    part_mask_path = resolve_part_mask_path(img_info, part_mask_dir)
    part_mask = np.array(Image.open(part_mask_path))
    if part_mask.ndim == 3:
        part_mask = part_mask[..., 0]

    patches = []
    for part_id in part_ids:
        pid = int(part_id)
        mask_value = pid + 1 if with_background_part else pid
        binary = (part_mask == mask_value)
        patch = crop_and_resize_binary_to_patch(
            binary_full=binary,
            crop_box_xyxy=crop_box,
            crop_dim=crop_dim,
            patch_size=patch_size,
        )
        patches.append(patch)

    if len(patches) == 0:
        grid = crop_dim // patch_size
        return torch.zeros((0, grid, grid), dtype=torch.bool)

    return torch.stack(patches, dim=0).bool()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_pth", required=True)
    parser.add_argument("--output_pth", required=True)
    parser.add_argument("--part_mask_dir", required=True)
    parser.add_argument("--crop_dim", type=int, default=448)
    parser.add_argument("--patch_size", type=int, default=14)
    parser.add_argument(
        "--with_background_part",
        action="store_true",
        default=False,
        help="Use this if part mask values are 1..num_parts with 0 as background. If false, part ids are 0-based.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        default=False,
        help="Overwrite existing part_gt_mask_patch if present.",
    )
    args = parser.parse_args()

    part_mask_dir = Path(args.part_mask_dir)
    if not part_mask_dir.exists():
        raise FileNotFoundError(f"part_mask_dir not found: {part_mask_dir}")

    print(f"[Load] {args.input_pth}")
    data = torch.load(args.input_pth, map_location="cpu")

    images_by_id = {img["id"]: img for img in data["images"]}

    n_written = 0
    n_skipped_existing = 0

    for ann in tqdm(data["annotations"], desc="add part_gt_mask_patch"):
        if "part_gt_mask_patch" in ann and not args.overwrite:
            n_skipped_existing += 1
            continue

        image_id = require_key(ann, "image_id", "annotation")
        if image_id not in images_by_id:
            raise KeyError(f"image_id={image_id} not found in images")

        img_info = images_by_id[image_id]

        gt_patch = build_part_gt_mask_patch_for_ann(
            ann=ann,
            img_info=img_info,
            part_mask_dir=part_mask_dir,
            crop_dim=args.crop_dim,
            patch_size=args.patch_size,
            with_background_part=args.with_background_part,
        )
        ann["part_gt_mask_patch"] = gt_patch
        n_written += 1

    out_dir = os.path.dirname(args.output_pth)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    torch.save(data, args.output_pth)
    print("========== Done ==========")
    print(f"input             : {args.input_pth}")
    print(f"output            : {args.output_pth}")
    print(f"part_mask_dir     : {args.part_mask_dir}")
    print(f"written           : {n_written}")
    print(f"skipped_existing  : {n_skipped_existing}")
    print(f"field_added       : part_gt_mask_patch")


if __name__ == "__main__":
    main()
